---
title: "Stat479_Portfollio4"
author: "Haoxuan Sun"
date: "5/4/2022"
output: pdf_document
---

```{r, warning = FALSE}
library(maps)
library(sf)
library(ggmap)
library(ggplot2)
library(tidyverse)
library(readr)
library(tsibble)
library(patchwork)

meteor = read_csv("meteorite-landings.csv")
```

```{r, message = FALSE}
#create a base ggplot object
g = ggplot() + 
  coord_fixed() + 
  xlab("longitude") + 
  ylab("latitude")

#specify the theme of maps
theme = theme(panel.grid.major = element_line(color = 2,
                                        size = 0.1,
                                        linetype = 2),
        panel.grid.minor = element_line(color = 2,
                                        size = 0.25,
                                        linetype = 1),
        panel.background = element_rect(fill = "white", colour = "white")
        )

#create a ggplot object contain map of US mainland
us_map = g + 
  geom_polygon(data = map_data("county"), 
               aes(long, lat, group = group), 
               col = "dark grey", 
               fill = "dark grey"
               ) + 
  theme

#create a ggplot object contain a world map
world_map = g + 
  geom_polygon(data = map_data("world"), 
               aes(long, lat, group = group), 
               col = "dark grey", 
               fill = "dark grey"
               ) + 
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0)) + 
  theme(panel.grid.major = element_line(color = 2,
                                        size = 0.1,
                                        linetype = 2),
        panel.grid.minor = element_line(color = 2,
                                        size = 0.25,
                                        linetype = 1),
        panel.background = element_rect(fill = "light blue", 
                                        colour = "light blue")
        )
```

```{r, message = FALSE}
#convert original data set into sf format
meteor_omit_sf = meteor %>% 
  na.omit() %>% 
  select(c(-GeoLocation)) %>% 
  st_as_sf(coords = c("reclong", "reclat"), crs = 4269) %>% 
  mutate_if(., is.character, as.factor) %>% 
  filter((year > 1925) & (year < 2014))

#convert original data set into tsibble format
meteor_omit_tsibble = meteor %>% 
  na.omit() %>% 
  group_by(year, fall) %>% 
  summarise(count = n()) %>% 
  mutate_if(., is.character, as.factor) %>% 
  filter((year > 1925) & (year < 2014))
```

###Visualization of Meteor Landing Spatial Data

```{r, warning = FALSE, message = FALSE, fig.height = 10, fig.width = 15}
#filter meteors which their landings are observed
meteor_Obs = meteor_omit_sf %>% 
  filter(fall == "Fell") %>% 
  mutate(fall = "Fall Observed")

#filter meteors which their landings are not observed
meteor_nObs = meteor_omit_sf %>%  
  filter(fall == "Found") %>% 
  mutate(fall = "Fall Not Observed")

#plot the global meteor landing maps, 
#size of the points is encoded with meteor size, 
#color of of the points is encoded with whether the meteor's landing is observed;
#blue is observed, red is non-observed
world_map_meteor = world_map + 
  geom_sf(data = meteor_Obs, 
          aes(size = log(mass, 2), 
          color = fall), 
          alpha = I(0.25)
          ) + 
  geom_sf(data = meteor_nObs, 
          aes(size = log(mass), 
          color = fall), 
          alpha = I(0.15)
          ) + 
  scale_color_manual(values = c("dark blue", "#C70039")) + 
  ggtitle("Global Meteorites From 1925 to 2013") + 
  labs(size = "Mass", color = "Observe")
world_map_meteor

#plot the meteor landing in the U.S. 
#size of the points is encoded with meteor size,
#color of the points is encoded with year
us_map_meteor = us_map + 
  geom_sf(data = meteor_omit_sf, 
          aes(color = year,
          size = log(mass, 2)), 
          alpha = I(0.3)
          ) + 
  scale_colour_distiller(palette = 8, direction = 1) + 
  coord_sf(xlim = c(-128, -62), 
           ylim = c(25, 50)
           ) + 
  ggtitle("Meteorites in US From 1925 to 2013") + 
  labs(size = "Mass")
us_map_meteor
```

###Visualization of Meteor Landing Time Series Data

```{r, message = FALSE, fig.width = 12, fig.height = 5}
#create a time series visualization with observed/non-observed meteors
meteor_omit_tsibble_1 = meteor_omit_tsibble %>% 
  filter(fall == "Fell") %>% 
  mutate(fall = "Fall Observed")

meteor_omit_tsibble_2 = meteor_omit_tsibble %>% 
  filter(fall == "Found") %>% 
  mutate(fall = "Fall Not Observed")

meteor_tsibble = rbind(meteor_omit_tsibble_1, meteor_omit_tsibble_2)

ggplot(meteor_tsibble) + 
  geom_line(aes(year, count, col = fall)) + 
  facet_wrap(.~ fall, scales = "free") + 
  scale_x_continuous(expand = c(0,0)) + 
  scale_y_continuous(expand = c(0,0)) + 
  theme_bw() + 
  scale_colour_manual(values = c("red", "blue")) + 
  ggtitle("Meteorite on Earth From 1925 to 2013") + 
  xlab("Year") + 
  ylab("Count")
```